# Generated by Django 5.2.12 on 2026-03-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialOutward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('entry_no', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('contents', models.CharField(max_length=100)),
                ('contents2', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('totalno', models.IntegerField()),
                ('vendor', models.CharField(max_length=100)),
                ('issuedto', models.CharField(max_length=100)),
                ('vehicleno', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=100)),
                ('returnable', models.BooleanField(default=False)),
                ('remarks', models.TextField()),
                ('acknowledgement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('rate', models.FloatField()),
                ('rackno', models.CharField(max_length=50)),
                ('critical_qty', models.IntegerField()),
                ('photo', models.ImageField(upload_to='materials')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.subcategory')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.unitmaster')),
                ('work_spots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.workspots')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('entry_no', models.IntegerField()),
                ('challan_no', models.CharField(max_length=50)),
                ('totalno', models.IntegerField()),
                ('rate', models.FloatField()),
                ('rackno', models.CharField(max_length=50)),
                ('total_stock', models.IntegerField()),
                ('receive_from', models.CharField(max_length=200)),
                ('vehicle_no', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materialmaster')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('entry_no', models.IntegerField()),
                ('requisition_no', models.CharField(max_length=50)),
                ('total_nos', models.IntegerField()),
                ('requisition_by', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materialmaster')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.subcategory')),
                ('work_spots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.workspots')),
            ],
        ),
    ]
