# Generated by Django 5.2.12 on 2026-05-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_materialreceipt_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialoutward',
            name='po',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='po',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
