# Generated by Django 5.2.12 on 2026-05-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_materialoutward_po_materialrequisition_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialreceipt',
            name='ledger_type',
            field=models.CharField(choices=[('receipt_ledger', 'Receipt Ledger'), ('return_inward', 'Return Inward')], default='receipt_ledger', max_length=50),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='ledger_type',
            field=models.CharField(choices=[('issue_ledger', 'Issue Ledger'), ('return_outward', 'Return Outward')], default='issue_ledger', max_length=50),
        ),
    ]
