# Generated by Django 5.2.12 on 2026-06-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_materialreceipt_ledger_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequisition',
            name='requisition_nos',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
